### ISSUE TITLE
手动添加信息时的报错

### ISSUE THREAD

**Issue by YoungJack068** [tongyifan/TJUPT-Anime-Autoseed#1]
添加副标题（small_descr）时，首位不能出现“[”和“]”，不然会出现yaml.parser.ParserError:while parsing a block mapping与did not find expected key的报错。

**Comment by tongyifan** [comment]
可以将副标题用英文双引号括起来，就可以加入这些特殊符号了

**Comment by YoungJack068** [comment]
因为订阅的内容少，还没有到更新的时候。只是把首位的“[”和“]”，换成了“【”和“】”。回头改了，我看一下效果~

**Comment by YoungJack068** [comment]
是我思想太僵化了，可以直接测试的，没有必要等待动漫更新……已经合适了，不会再报错了。多谢大佬指点~
