### ISSUE TITLE
可以适配其他站点吗？

### ISSUE THREAD

**Issue by YoungJack068** [tongyifan/TJUPT-Anime-Autoseed#2]
想去自动转种，或者发种到其他站点，也是NexusPHP构架的。可以实现吗？

**Comment by tongyifan** [comment]
如[README中所述](https://github.com/tongyifan/TJUPT-Anime-Autoseed/blob/master/README.md#%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E)，可以自行对autoseed.py进行修改

**Comment by YoungJack068** [comment]
> 如[README中规定](https://github.com/tongyifan/TJUPT-Anime-Autoseed/blob/master/README.md#%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E)，可以自行对autoseed.py进行修改

尝试了一下，失败了，估计是有没有注意的地方/(ㄒoㄒ)/~~
